### ISSUE TITLE
/convert no longer works in new discord

### ISSUE THREAD

**Issue by HugoVG** [Thibstars/Currency-Converter-Bot#276]
**Describe the bug**
using /convert int string string no longer works 

**To Reproduce**
1. Typing /convert int string string

**Expected behavior**
it to work

**Comment by Thibstars** [comment]
Thanks for the report. I'm sorry for the late reaction, I totally missed this one. I have tested this again and it seems to work perfectly fine in a Discord instance that I have just updated.

Do you still encounter this problem?

**Comment by Thibstars** [comment]
Closing issue now due to lack of activity. The bot got a few updates in the meantime, so please make a new ticket if you still encounter issues.
